KEYBOARD using HTML and CSS
hackslash-nitp/css-art pull request #12
Opened 2020-05-14 19:17 UTC by dev-amrit460

2020-05-14 19:24 UTC, dev-amrit460 commented
Sir,
Is it ok now?

2020-05-20 19:58 UTC, krharsh17 requested changes
Replace `krharsh17` with your username for all files. You have to make a folder by your username and put files in it. You've made a folder with my username currently

2020-05-21 03:59 UTC, dev-amrit460 commented
sir, I renamed that......

2020-05-21 17:48 UTC, krharsh17 approved these changes

2020-05-21 17:48 UTC, merged